import os

API_KEY = os.environ.get('API_KEY')
API_SECRET = os.environ.get('API_SECRET')
ACCESS_TOKEN = os.environ.get('ACCESS_TOKEN')
ACCESS_TOKEN_SECRET = os.environ.get('ACCESS_TOKEN_SECRET')

MAX_TWEET_LENGTH = 280
MAX_TITLE_LENGTH = 25
MAX_TWEET_CONTENT_LENGTH = MAX_TWEET_LENGTH - MAX_TITLE_LENGTH - 2
